# Generated by Django 5.1.7 on 2025-05-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_grade_letter_grade_alter_grade_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this student is active or not.'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('M', 'Midterm'), ('F', 'Final'), ('P', 'Project')], default='L', max_length=1),
        ),
    ]
